Public Class Form1

    
    Private Sub Label12_Click(sender As Object, e As EventArgs) Handles Label12.Click

    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'Lets set all of our tooltips
        toolTip1.SetToolTip(txtBox_id, "This will be generated by the system for you.")
        toolTip1.SetToolTip(txtBox_Name, "Enter your First & Second names in here.")
        'toolTip1.SetToolTip(textBox_dob, "Select the age range you fit in, this is not required.")
        toolTip1.SetToolTip(txtBox_addr1, "Please enter the first line of your postal address.")
        toolTip1.SetToolTip(txtBox_addr2, "Optional, the second line of your postal address.")
        toolTip1.SetToolTip(txtBox_post, "Required, your postcode")
        toolTip1.SetToolTip(txtBox_occ, "Your Occupation, select from the list.")
        toolTip1.SetToolTip(txtBox_tel, "Either your Telephone or Mobile number.")
        toolTip1.SetToolTip(txtBox_town, "The town your postal address is in.")
        toolTip1.SetToolTip(txtBox_email, "Your email address.")
        toolTip1.SetToolTip(txtBox_com, "The company you work for, only required for when you are a company representative.")
        toolTip1.SetToolTip(txtBox_refer, "How did you find out about this event?.")
    End Sub

End Class
