Public Class Main
    Public Shared records(0) As String
    Public Shared eventName As String = "Minecraft Day!"
    '(C) Ryan Walmsley
    'All code is licensed under the GNU GPL V3 License
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'Call the function to load all the data
        loadFromTextFile()
        'Lets set all of our tooltips
        toolTip1.SetToolTip(txtBox_id, "This will be generated by the system for you.")
        toolTip1.SetToolTip(txtBox_Name, "Enter your First & Second names in here.")
        toolTip1.SetToolTip(dropDown_dob, "Select the age range you fit in, this is not required.")
        toolTip1.SetToolTip(txtBox_addr1, "Please enter the first line of your postal address.")
        toolTip1.SetToolTip(txtBox_addr2, "Optional, the second line of your postal address.")
        toolTip1.SetToolTip(txtBox_post, "Required, your postcode")
        toolTip1.SetToolTip(dropDown_occ, "Please select your occupation")
        toolTip1.SetToolTip(txtBox_tel, "Either your Telephone or Mobile number.")
        toolTip1.SetToolTip(txtBox_town, "The town your postal address is in.")
        toolTip1.SetToolTip(txtBox_email, "Your email address.")
        toolTip1.SetToolTip(txtBox_com, "The company you work for, only required for when you are a company representative.")
        toolTip1.SetToolTip(dropDown_ref, "How did you find out about this event?.")

        'Lets reset the first tab
        reset_tab1()
        'And on the second tab update the ticket
        updateTicket()
    End Sub


    Private Sub dropDown_occ_SelectedIndexChanged(sender As Object, e As EventArgs) Handles dropDown_occ.SelectedIndexChanged
        'We want to make the company name editable if occupation is company rep
        If (dropDown_occ.SelectedIndex = 0) Then
            txtBox_com.Enabled = True

        Else
            txtBox_com.Enabled = False

        End If

    End Sub




    Private Sub button_print_Click(sender As Object, e As EventArgs) Handles button_print.Click
        print_ticket_document.DocumentName = "lbl_Ticket"

        print_ticket_dialog.Document = print_ticket_document
        If print_ticket_dialog.ShowDialog() = Windows.Forms.DialogResult.OK Then
            print_ticket_document.PrinterSettings = print_ticket_document.PrinterSettings
            print_ticket_document.Print()
        Else
            MsgBox("Unknown Error printing")
        End If


    End Sub


    Private Sub print_ticket_document_PrintPage(sender As Object, e As Printing.PrintPageEventArgs) Handles print_ticket_document.PrintPage
        Dim prFont As New Font("Consolas", 18, GraphicsUnit.Point)
        e.Graphics.DrawString(lbl_Ticket.Text, prFont, Brushes.Black, 50, 50)
    End Sub

    Private Sub button_submit_Click(sender As Object, e As EventArgs) Handles button_submit.Click
        Dim errors As Integer = 0
        Dim errorString As String = ""
        'Register Button has been pushed

        'Validate Full Name
        If (txtBox_Name.Text.Length < 5) Then
            errors = 1
            errorString = errorString + "The full name must be at least 5 Alpha Numeric Characters." + vbCrLf
        End If

        'Date of birth must not be = ""
        If (dropDown_dob.Text = "Select") Then
            errors = 1
            errorString = errorString + "You must select a date of birth date range." + vbCrLf
        End If
        'Address line 1 must have 5 alphanumeric
        If (txtBox_addr1.Text.Length < 5) Then
            errors = 1
            errorString = errorString + "You must have 5 alpha numeric characters for your address " + vbCrLf
        End If
        'Ignore address line 2
        'Postcode validation, at least 6 chars
        If (txtBox_tel.Text.Length < 6 Or txtBox_post.Text.Length > 8) Then
            errors = 1
            errorString = errorString + "You must have between 6-8 alpha numeric characters for the postcode" + vbCrLf
        End If

        'Town Validation
        If (txtBox_town.Text.Length< 5) Then
            errors = 1
            errorString = errorString + "The town must have 5 alpha numeric characters." + vbCrLf

        End If

        'Telephone Validation
        If (txtBox_tel.Text.Length < 11) Then
            errors = 1
            errorString = errorString + "The telephone must have 11 digits" + vbCrLf
        End If

        'Email validation
        'Split into array for first section
        Dim emailPart1(1) As String
        emailPart1 = Split(txtBox_email.Text, "@")
        'Then split the second half by the .
        If (emailPart1.Length > 1) Then
            Dim emailPart2(2) As String
            emailPart2 = Split(emailPart1(1), ".")
            If (emailPart1(1).Length < 1 Or emailPart2(0).Length < 1 Or emailPart2(1).Length < 1) Then
                errors = 1
                errorString = errorString + "Email is invalid, please check it" + vbCrLf
            End If
        Else
            errors = 1
            errorString = errorString + "Email is invalid, please check it" + vbCrLf
        End If

        
        'Dropbox occupation
        If (dropDown_occ.Text = "Select") Then
            errors = 1
            errorString = errorString + "You must select an occupation." + vbCrLf
        End If
        'Company
        If (dropDown_occ.Text= "Company Rep") Then
            If (txtBox_com.Text.Length < 5) Then
                errors = 1
                errorString = errorString + "You must enter your company name." + vbCrLf
            End If
        End If
        If (dropDown_ref.Text = "Select") Then
            errors = 1
            errorString = errorString + "You must tell us how you found out about the event." + vbCrLf
        End If

        'Then if no errors save record then reset
        If (errors = 0) Then
            'Do stuff
            'Save the ticket! 
            'We only need to save "Ryan Walmsley,Student,IT Gaming Event,04/04/2014,Ryanteck LTD."
            Dim newTicket As String
            newTicket = txtBox_Name.Text + "," + dropDown_occ.SelectedIndex.ToString + "," + eventName + "," + Date.Today.ToString + "," + txtBox_com.Text
            'Now add it as a new record
            Dim id As Integer = records.Length
            ReDim Preserve records(id)
            records(id) = newTicket
            'Finally re-write all tickets to txt
            writeTickets()


            'Reset the tab
            reset_tab1()
        Else
            MsgBox(errorString, 0, "An Error Occured")
        End If



    End Sub

    Private Sub reset_tab1()
        'Reset the full name to ""
        txtBox_Name.Text = ""
        'set date of birth to "Select"
        dropDown_dob.Text = "Select"
        'Set Address lines 1 & 2 to ""
        txtBox_addr1.Text = ""
        txtBox_addr2.Text = ""
        'Postcode reset
        txtBox_post.Text = ""
        'Town Reset
        txtBox_town.Text = ""
        'Telephone Reset
        txtBox_tel.Text = ""
        'Email Reset
        txtBox_email.Text = ""
        'Dropbox occupation
        dropDown_occ.Text = "Select"
        'Company
        txtBox_com.Text = "N/A"
        'Refer
        dropDown_ref.Text = "Select"
        'Disable company rep box
        txtBox_com.Enabled = False
        'Set email to default, rest as none
        radio_Email.Checked = True
        radio_phone.Checked = False
        radio_post.Checked = False
        radio_sms.Checked = False
        'Finally get a new ID
        txtBox_id.Text = records.Length.ToString("D4")
        'Oh and set the maximum ID Number
        spinner_Id.Maximum = (records.Length - 1)
    End Sub




    Private Sub spinner_Id_ValueChanged(sender As Object, e As EventArgs) Handles spinner_Id.ValueChanged
        updateTicket()
    End Sub
    Private Sub updateTicket()
        'Value has been changed, update the record
        'First get the ticket record from the spinner's ID
        Dim ticketData As String = records(spinner_Id.Value)
        'Then split the ticket record into each component
        Dim ticketArray(0) As String
        ticketArray = Split(ticketData, ",")
        'Get the ID of the ticket based on the spinner
        Dim ticketID As Integer = spinner_Id.Value
        'Dim the ticket which will then contain the ticket's data
        Dim ticket As String
        'Set the unique ID and have 4 digits
        ticket = "Unique ID: " + ticketID.ToString("D4")
        ticket = ticket + vbCrLf + "Full Name: " + ticketArray(0) 'Add the name
        ticket = ticket + vbCrLf + "Occupation: " + ticketArray(1) ' Add the Occupation
        ticket = ticket + vbCrLf + "Event: " + ticketArray(2) ' Add the event name
        ticket = ticket + vbCrLf + "Date: " + ticketArray(3) ' Add the date
        If (ticketArray(4) <> "N/A") Then
            ticket = ticket + vbCrLf + "Company Name: " + ticketArray(4) ' The user's company is not N/A so add to ticket
        End If


        lbl_Ticket.Text = ticket 'Finally output the tickets data to the screen

    End Sub

    Private Sub loadFromTextFile()
        'Set the data file as a glob
        Dim storageFile As String = "recordStorage.txt"
        'Storage file
        Dim rawData As String

        rawData = My.Computer.FileSystem.ReadAllText(storageFile)
        rawData = rawData.Substring(0, (rawData.Length - 1))
        records = Split(rawData, ";")
    End Sub

    Private Sub btn_Reload_Click(sender As Object, e As EventArgs) Handles btn_Reload.Click
        'This just force reloads from file
        loadFromTextFile()
        updateTab3()
    End Sub

    Private Sub writeTickets()
        Dim newTicketFile As String = ""
        Dim storageFile As String = "recordStorage.txt"
        For Each ticket As String In records
            newTicketFile = newTicketFile + ticket + ";"
        Next
        My.Computer.FileSystem.WriteAllText(storageFile, newTicketFile, False)
    End Sub

    Private Sub updateTab3()
        Dim Ticket As String
        Dim TicketArray(0) As String
        Dim uniqueid As Integer = 0
        For Each ticketData As String In records
            TicketArray = Split(ticketData, ",")
            Ticket = TicketArray(0) + "," + TicketArray(1) + "," + TicketArray(4) + "," + uniqueid.ToString("D4")
            list_Tab3.Items.Add(Ticket)
            uniqueid = uniqueid + 1
        Next


    End Sub

End Class
